/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Enumeracion.Permiso;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import logica.Banco;
import logica.Cliente;

/**
 * @author Alejandro
 * @author Shonny
 * @author Juan Camilo
 */
public class VentanaCrearClienteAdmin extends javax.swing.JFrame {

    private Banco miBanco;
    private Cliente miCliente;

    /**
     * Creates new form VentanaCrearCliente
     *
     * @param ban
     */
    public VentanaCrearClienteAdmin(Banco ban) {
        miBanco = ban;
        initComponents();
        setLocationRelativeTo(null);

//        jComboBoxPermisoAdmin.setModel(new DefaultComboBoxModel(Permiso.values()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBagregarUsuario = new javax.swing.JButton();
        jTnombreUsuario = new javax.swing.JTextField();
        jTapellidoUsuario = new javax.swing.JTextField();
        jTcedulaUsuario = new javax.swing.JTextField();
        jCsexoUsuario = new javax.swing.JComboBox<>();
        jTemailUsuario = new javax.swing.JTextField();
        jDateFechaNacimiento = new com.toedter.calendar.JDateChooser();
        jTusuarioCrearUsuario = new javax.swing.JTextField();
        jTrespuestaUsuario = new javax.swing.JTextField();
        jPasswordUsuario = new javax.swing.JPasswordField();
        jTpreguntaCrearUsuario = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPermisoAdmin = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("VentanaCrearClienteAdmin.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(bundle.getString("NOMBRE:")); // NOI18N

        jLabel2.setText(bundle.getString("APELLIDOS:")); // NOI18N

        jLabel3.setText(bundle.getString("CEDULA:")); // NOI18N

        jLabel5.setText(bundle.getString("SEXO:")); // NOI18N

        jLabel6.setText(bundle.getString("EMAIL:")); // NOI18N

        jLabel7.setText(bundle.getString("FECHA NACIMIENTO:")); // NOI18N

        jLabel8.setText(bundle.getString("USUARIO:")); // NOI18N

        jLabel9.setText(bundle.getString("CONTRASEÑA:")); // NOI18N

        jLabel10.setText(bundle.getString("PREGUNTA:")); // NOI18N

        jLabel11.setText(bundle.getString("RESPUESTA:")); // NOI18N

        jBagregarUsuario.setText(bundle.getString("AGREGAR USUARIO")); // NOI18N
        jBagregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarUsuarioActionPerformed(evt);
            }
        });

        jTnombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnombreUsuarioKeyTyped(evt);
            }
        });

        jTapellidoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTapellidoUsuarioKeyTyped(evt);
            }
        });

        jTcedulaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTcedulaUsuarioKeyTyped(evt);
            }
        });

        jCsexoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino ", "Femenino" }));

        jTpreguntaCrearUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "¿Cómo se llama su mascota?", "¿Cuál es el nombre de su madre?", "¿Nombre de su mejor amig@?", "¿Cuál es su comida favorita?", "¿Primer nombre de su padre?" }));

        jLabel4.setText(bundle.getString("VentanaCrearClienteAdmin.jLabel4.text")); // NOI18N

        jComboBoxPermisoAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "ADMIN" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBagregarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTapellidoUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTcedulaUsuario)
                            .addComponent(jTnombreUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(jTusuarioCrearUsuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCsexoUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTemailUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTrespuestaUsuario)
                            .addComponent(jPasswordUsuario)
                            .addComponent(jTpreguntaCrearUsuario, 0, 298, Short.MAX_VALUE)
                            .addComponent(jComboBoxPermisoAdmin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTnombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTapellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTcedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCsexoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTemailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTusuarioCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTpreguntaCrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTrespuestaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxPermisoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBagregarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBagregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarUsuarioActionPerformed
        // TODO add your handling code here:
        if (ValidarDatosAgregarJugador().equals("")) {
            String nombres = jTnombreUsuario.getText();
            String apellidos = jTapellidoUsuario.getText();
            String cedula = jTcedulaUsuario.getText();
            int edad = calcularEdad();
            String sexo = (String) jCsexoUsuario.getSelectedItem();
            String email = jTemailUsuario.getText();
            Date fechaCumpleanios = jDateFechaNacimiento.getCalendar().getTime();
            String usuario = jTusuarioCrearUsuario.getText();
            char[] obtenerPassword = jPasswordUsuario.getPassword();
            String password = "";
            for (int i = 0; i < obtenerPassword.length; i++) {
                password += obtenerPassword[i];
            }
            String preguntaSeguridad = (String) jTpreguntaCrearUsuario.getSelectedItem();
            String respuestaUsuario = jTrespuestaUsuario.getText();

            String permiso = (String) jComboBoxPermisoAdmin.getSelectedItem();
            Permiso permisoEnum = Permiso.valueOf(permiso);

            miCliente = new Cliente(nombres, apellidos, cedula, edad, sexo, email, fechaCumpleanios, usuario, password, preguntaSeguridad, respuestaUsuario, permisoEnum);

            //llamamos el metodo agregar cliente
            boolean agregarClient = miBanco.agregarCliente(miCliente);

            //Mostramos mensaje de que se agrego o no el Cliente
            if (agregarClient) {
                JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("EL CLIENTE SE AGREGÓ"));
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("NO SE PUEDE AGREGAR EL CLIENTE"));
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, java.text.MessageFormat.format(java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("ERROR!!! "), new Object[]{ValidarDatosAgregarJugador()}), java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("VALIDANDO DATOS"),
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBagregarUsuarioActionPerformed

    private void jTnombreUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnombreUsuarioKeyTyped
        // TODO add your handling code here:
        validarLetras(jTnombreUsuario, evt);
    }//GEN-LAST:event_jTnombreUsuarioKeyTyped

    private void jTapellidoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTapellidoUsuarioKeyTyped
        // TODO add your handling code here:
        validarLetras(jTapellidoUsuario, evt);
    }//GEN-LAST:event_jTapellidoUsuarioKeyTyped

    private void jTcedulaUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTcedulaUsuarioKeyTyped
        // TODO add your handling code here:
        validarNumeros(jTcedulaUsuario, evt);
    }//GEN-LAST:event_jTcedulaUsuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearClienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearClienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearClienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearClienteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearClienteAdmin(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregarUsuario;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBoxPermisoAdmin;
    private javax.swing.JComboBox<String> jCsexoUsuario;
    private com.toedter.calendar.JDateChooser jDateFechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordUsuario;
    private javax.swing.JTextField jTapellidoUsuario;
    private javax.swing.JTextField jTcedulaUsuario;
    private javax.swing.JTextField jTemailUsuario;
    private javax.swing.JTextField jTnombreUsuario;
    private javax.swing.JComboBox<String> jTpreguntaCrearUsuario;
    private javax.swing.JTextField jTrespuestaUsuario;
    private javax.swing.JTextField jTusuarioCrearUsuario;
    // End of variables declaration//GEN-END:variables

    /**
     * metodo que sirve para validar numeros y este es llamado cuando existe un
     * evento de teclado
     *
     * @param campo campo al cual se aplica la validacion
     * @param evt evento de teclado
     */
    public void validarNumeros(JTextField campo, KeyEvent evt) {
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("NO PUEDE INGRESAR LETRAS!!!"), java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("VALIDANDO DATOS"),
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        } else if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("NO PUEDE INGRESAR SIMBOLOS!!!"), java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("VALIDANDO DATOS"),
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        }
    }

    /**
     * metodo que sirve para validar letras y este es llamado cuando existe un
     * evento de teclado
     *
     * @param campo campo al cual se aplica la validacion
     * @param evt evento de teclado
     */
    public void validarLetras(JTextField campo, KeyEvent evt) {
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("NO PUEDE INGRESAR NUMEROS!!!"), java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("VALIDANDO DATOS"),
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        } else if ((int) evt.getKeyChar() > 32 && (int) evt.getKeyChar() <= 47
                || (int) evt.getKeyChar() >= 58 && (int) evt.getKeyChar() <= 64
                || (int) evt.getKeyChar() >= 91 && (int) evt.getKeyChar() <= 96
                || (int) evt.getKeyChar() >= 123 && (int) evt.getKeyChar() <= 255) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("NO PUEDE INGRESAR SIMBOLOS!!!"), java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("VALIDANDO DATOS"),
                    JOptionPane.INFORMATION_MESSAGE);
            campo.setCursor(null);
        }
    }

    /**
     * metodo que sirve para validar que los campos no esten vacios
     *
     * @return un mensaje de error dependiendo si el campo esta vacio
     */
    public String ValidarDatosAgregarJugador() {//Metodo para comprobar que los datos esten completos
        String msj = "";
        if (jTnombreUsuario.getText().equals("")) {//Si jTnombreUsuario esta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR DIGITE EL NOMBRE.");
        }
        if (jTapellidoUsuario.getText().equals("")) {//Si jTapellidoUsuario esta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR DIGITE EL APELLIDO.");
        }
        if (jTcedulaUsuario.getText().equals("")) {//Si jTcedulaUsuarioesta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR DIGITE LA CEDULA.");
        }
        if (jTemailUsuario.getText().equals("")) {//Si jTemailUsuario esta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR DIGITE EL EMAIL.");
        }
        if (jDateFechaNacimiento.getCalendar() == null) {//Si jDateFechaNacimiento esta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR SELECCIONE UNA FECHA.");
        }
        if (jTusuarioCrearUsuario.getText().equals("")) {//Si jTusuarioCrearUsuario esta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR DIGITE EL USUARIO.");
        }

        if (jPasswordUsuario.getPassword().length == 0) {//Si jPasswordUsuario esta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR DIGITE UNA CONTRASEÑA");
        }
        if (jTrespuestaUsuario.getText().equals("")) {//Si jTrespuestaUsuario esta vacio
            msj += java.util.ResourceBundle.getBundle("properties/VentanaCrearCliente").getString("POR FAVOR DIGITE UNA RESPUESTA");
        }
        return msj;//devuelve msj
    }

    /**
     *
     * @return
     */
    public int calcularEdad() {
        int edad;
        Calendar fecha = jDateFechaNacimiento.getCalendar();
        int anoNacimiento = fecha.get(Calendar.YEAR);
        int mesNacimiento = fecha.get(Calendar.MONTH) + 1;
        int diaNacimiento = fecha.get(Calendar.DAY_OF_MONTH);

        Calendar actual = Calendar.getInstance();
        int anoActual = actual.get(Calendar.YEAR);
        int mesActual = actual.get(Calendar.MONTH) + 1;
        int diaActual = actual.get(Calendar.DAY_OF_MONTH);

        //si el mes es el mismo pero el dia inferior aun no ha cumplido años, le quitaremos un año al actual 
        if (mesNacimiento == mesActual && diaNacimiento > diaActual) {
            anoActual = (anoActual - 1);
            edad = anoActual - anoNacimiento;
            return edad;
            //si el mes es superior al actual tampoco abra cumplido años, por eso le quitamos un año al actual 
        } else if (mesNacimiento > mesActual) {
            anoActual = (anoActual - 1);
            edad = anoActual - anoNacimiento;
            return edad;
            //ya no habria mas condiciones, ahora simplemente restamos los años y mostramos el resultado 
        } else {
            edad = anoActual - anoNacimiento;
            return edad;
        }
    }

}
