/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import logica.Banco;
import logica.Cliente;
import logica.Empresa;
import static vista.VentanaPrincipal.*;

/**
 * @author Juan Carlos
 * @author Shonny
 * @author Juan Carlos
 */
public class VentanaLogin extends javax.swing.JFrame {

    private Banco miBanco;
    private Cliente miCliente;

    /**
     * Creates new form Login
     * @param ban
     */
    public VentanaLogin(Banco ban) {
        miBanco = ban;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTusuarioLogin = new javax.swing.JTextField();
        jBIniciarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordLogin = new javax.swing.JPasswordField();
        jCheckBoxEmpresa = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("properties/VentanaLogin"); // NOI18N
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("VentanaLogin.jPanel1.border.title"))); // NOI18N

        jTusuarioLogin.setToolTipText(bundle.getString("USUARIO")); // NOI18N

        jBIniciarSesion.setText(bundle.getString("INICIAR SESIÓN")); // NOI18N
        jBIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIniciarSesionActionPerformed(evt);
            }
        });

        jLabel2.setText(bundle.getString("USUARIO:")); // NOI18N

        jLabel3.setText(bundle.getString("CONTRASEÑA:")); // NOI18N

        jCheckBoxEmpresa.setText(bundle.getString("EMPRESA")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTusuarioLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jPasswordLogin)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCheckBoxEmpresa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jBIniciarSesion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTusuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBIniciarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIniciarSesionActionPerformed
        // TODO add your handling code here:
        String usuario = jTusuarioLogin.getText();
        char[] obtenerPassword = jPasswordLogin.getPassword();
        String password = "";
        for (int i = 0; i < obtenerPassword.length; i++) {
            password += obtenerPassword[i];
        }
        if (jCheckBoxEmpresa.isSelected()) {
            Empresa empresa = miBanco.buscarEmpresaPorUsuario(usuario);
            if (empresa != null&& empresa.getPassword().equals(password)) {
                VentanaPrincipal.jLabelUsuarioSesion.setVisible(true);
                VentanaPrincipal.jLabelUsuarioSesion.setText(empresa.getUsuario());
                jMenuLogin.setVisible(false);
                jMenuCuenta.setVisible(true);

                VentanaPrincipal.bandera = true;
                //llamamos al metodo
                permisos(empresa.getPermisos().name());
                //prueba de mandar el objeto de sesion
                VentanaPrincipal.empresaSesion = empresa;
                setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaLogin").getString("LA EMPRESA NO EXISTE"));
            }
        } else {
            Cliente cliente = miBanco.buscarClientePorUsuario(usuario);
            if (cliente != null && cliente.getPassword().equals(password)) {
                
                VentanaPrincipal.jLabelUsuarioSesion.setVisible(true);
                VentanaPrincipal.jLabelUsuarioSesion.setText(cliente.getUsuario());
                
                jMenuLogin.setVisible(false);
                jMenuCuenta.setVisible(true);
                VentanaPrincipal.bandera = false;
                
                //llamamos al metodo
                permisos(cliente.getPermisos().name());

                //prueba de mandar el objeto de sesion
                VentanaPrincipal.clienteSesion = cliente;
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/VentanaLogin").getString("EL CLIENTE NO EXISTE"));
            }
        }

    }//GEN-LAST:event_jBIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIniciarSesion;
    private javax.swing.JCheckBox jCheckBoxEmpresa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordLogin;
    private javax.swing.JTextField jTusuarioLogin;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param permiso
     */
    public void permisos(String permiso) {
        jMenuCuenta.setVisible(true);
        if ("CLIENTE".equals(permiso)) {
            jMenuUsuarioAdmin.setVisible(false);
            jMenuUsuarioEmpresa.setVisible(false);
        }else if("EMPRESA".equals(permiso)){
            jMenuUsuarioAdmin.setVisible(false);
            jMenuIUsuario.setVisible(false);
        }else{
            jMenuUsuarioEmpresa.setVisible(false);
            jMenuIUsuario.setVisible(false);
        }
    }

    /**
     *
     */
    public void inicializarCampo() {
        //codigo para no mostrar algunos elementos cuando inicie el programa
    }
}
