/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Enumeracion.Permiso;
import java.util.Date;
import javax.swing.JOptionPane;
import logica.Ahorro;
import logica.Banco;
import logica.Cliente;
import logica.Corriente;
import logica.Empresa;
import logica.Nomina;
import static vista.VentanaPrincipal.clienteSesion;

/**
 * @author Alejandro
 * @author Shonny
 * @author Juan Carlos
 */
public class VentanaModificarCuentaAdmin extends javax.swing.JFrame {

    private Banco miBanco;
    private Ahorro miAhorro;
    private Corriente miCorriente;
    private Nomina miNomina;
    private Empresa miEmpresa;
    private Cliente miCliente;
    private String idCuenta;
    private String idCliente;
    private boolean ahorro;
    private boolean corriente;

    private Date feCreacion;

    /**
     * Creates new form VentanaCrearCuenta
     *
     * @param ban
     * @param id
     * @param ahorro
     * @param corriente
     *
     */
    public VentanaModificarCuentaAdmin(Banco ban, String idCliente, String idCuenta, boolean ahorro, boolean corriente) {
        miBanco = ban;
        this.idCuenta = idCuenta;
        this.idCliente = idCliente;
        this.ahorro = ahorro;
        this.corriente = corriente;

        initComponents();
        setLocationRelativeTo(null);
        miCliente = miBanco.buscarCliente(idCliente);

        inicializarCampos();
        bloquearTxt();

//        System.out.println(miAhorro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCuentas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLMonto = new javax.swing.JLabel();
        jLNIT = new javax.swing.JLabel();
        jLFechaRetiro = new javax.swing.JLabel();
        jTMonto = new javax.swing.JTextField();
        jTNIT = new javax.swing.JTextField();
        jDateFechaRetiro = new com.toedter.calendar.JDateChooser();
        jBModificarCuenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTNumeroCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Cuenta"));

        jLMonto.setText("Monto:");

        jLNIT.setText("NIT:");

        jLFechaRetiro.setText("Fecha Retiro:");

        jBModificarCuenta.setText("Modificar Cuenta");
        jBModificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarCuentaActionPerformed(evt);
            }
        });

        jLabel1.setText("# Cuenta:");

        jTNumeroCuenta.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jBModificarCuenta))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLFechaRetiro)
                                .addGap(18, 18, 18)
                                .addComponent(jDateFechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLNIT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLMonto)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTNumeroCuenta)
                                    .addComponent(jTMonto, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTNumeroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLMonto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNIT))
                        .addGap(18, 18, 18)
                        .addComponent(jDateFechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLFechaRetiro))
                .addGap(18, 18, 18)
                .addComponent(jBModificarCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBModificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarCuentaActionPerformed
        // TODO add your handling code here:
//        if (validarDatos().equals("")) {

        String nit = jTNIT.getText();

        if (ahorro) {
            //selecciono ahorro
            double monto = Double.parseDouble(jTMonto.getText());
            Date fechaRetiro = jDateFechaRetiro.getCalendar().getTime();
            String numeroAhorro = jTNumeroCuenta.getText();

            boolean modificarAhorro = miCliente.modificarCuentaAhorro(idCuenta, fechaRetiro, monto, numeroAhorro);
            //revisar lo hizo juank, los usuarios no tienen numeros bancario tienen cuentas...
            miCliente.setNumeroBancario(numeroAhorro);

            //Mostramos mensaje de que se agrego o no la cuneta de ahorros
            if (modificarAhorro) {
                JOptionPane.showMessageDialog(null, "La cuenta de Ahorros se modifico");
//                    VentanaCuentaUsuario.llenarTablaAhorro();
            } else {
                JOptionPane.showMessageDialog(null, "No se puede modificar la cuenta de Ahorros");
            }

        } else if (corriente) {
            //selecciono corriente
            double monto = Double.parseDouble(jTMonto.getText());
            String numeroCorriente = jTNumeroCuenta.getText();

            boolean modificarCorriente = miCliente.modificarCuentaCorriente(idCuenta, monto, numeroCorriente);

            miCliente.setNumeroBancario(numeroCorriente);

            //Mostramos mensaje de que se agrego o no la cuneta de ahorros
            if (modificarCorriente) {
                JOptionPane.showMessageDialog(null, "La cuenta Corriente se modifico");
//                    VentanaCuentaUsuario.llenarTablaCorriente();
            } else {
                JOptionPane.showMessageDialog(null, "No se puede modificar la cuenta Corriente");
            }

        } else {
            //selecciono nomina
            miEmpresa = miBanco.buscarEmpresa(nit);

            if (miEmpresa != null) {
//                String nitNom = jTNIT.getText();
                double monto = Double.parseDouble(jTMonto.getText());

                boolean modificarNomina = miCliente.modificarCuentaNomina(idCuenta, miEmpresa, monto);

                if (modificarNomina) {
                    JOptionPane.showMessageDialog(null, "La cuenta Nomina se modifico");

                } else {
                    JOptionPane.showMessageDialog(null, "No se puede modificar la cuenta Nomina");

                }

            } else {
                JOptionPane.showMessageDialog(null, "La empresa no existe");
            }

        }

//        } else {
////            JOptionPane.showMessageDialog(rootPane, "ERROR!!! \n" + validarDatos(), "Validando Datos",
////                    JOptionPane.INFORMATION_MESSAGE);
//        }
    }//GEN-LAST:event_jBModificarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaModificarCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificarCuentaAdmin(null, null, null, false, false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCuentas;
    private javax.swing.JButton jBModificarCuenta;
    private com.toedter.calendar.JDateChooser jDateFechaRetiro;
    private javax.swing.JLabel jLFechaRetiro;
    private javax.swing.JLabel jLMonto;
    public static javax.swing.JLabel jLNIT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTMonto;
    private javax.swing.JTextField jTNIT;
    private javax.swing.JTextField jTNumeroCuenta;
    // End of variables declaration//GEN-END:variables

//    private String validarDatos() {
//        String msj = "";
//        if (!jRadioAhorro.isSelected() && !jRadioCorriente.isSelected() && !jRadioNomina.isSelected()) {
//            msj += "Por favor Seleccione un tipo de cuenta";
//        }
//        if (jRadioAhorro.isSelected()) {
//            if (jTMonto.getText().equals("")) {
//                msj += "Por favor digite el Monto con el que va a empezar la cuenta de ahorro.\n";
//            }
//            if (jDateFechaRetiro.getCalendar() == null) {//Si jDateFechaNacimiento esta vacio
//                msj += "Por favor seleccione una fecha.";
//            }
//        }
//
//        if (jRadioCorriente.isSelected()) {
//            if (jTMonto.getText().equals("")) {//Si jTMonto esta vacio
//                msj += "Por favor digite el Monto con el que va a empezar la cuenta corriente.\n";
//            }
//        }
//
//        if (jRadioNomina.isSelected()) {
//            if (jTNIT.getText().equals("")) {//Si jTNIT esta vacio
//                msj += "Por favor digite el NIT de la empresa.";
//            }
//        }
//        return msj;
//    }
    public void inicializarCampos() {
        if (ahorro) {
            miAhorro = miCliente.buscarCuentaAhorro(idCuenta);
            jTNumeroCuenta.setText(miAhorro.getNumeroBancario());
            jTMonto.setText(miAhorro.getMonto() + "");
            jDateFechaRetiro.setDate(miAhorro.getFechaRetiroAhorros());

        } else if (corriente) {
            miCorriente = miCliente.buscarCuentaCorriente(idCuenta);
            jTNumeroCuenta.setText(miCorriente.getNumeroBancario());
            jTMonto.setText(miCorriente.getMonto() + "");
            
        } else {
            miNomina = miCliente.buscarCuentaNomina(idCuenta);
            jTNumeroCuenta.setText(miNomina.getNumeroBancario());
            jTMonto.setText(miNomina.getMonto() + "");
            jTNIT.setText(miNomina.getEmpresa().getNIT());

        }

    }
//    public void inicializarCliente(){
//        if (ahorro) {
//            miCliente = miBanco.buscarCliente(idCliente);
//        } else if (corriente) {
//            miCliente = miBanco.buscarCliente(idCliente);
//        }
//    }

    public void bloquearTxt() {
        jTNIT.setEnabled(false);
        jDateFechaRetiro.setEnabled(false);
        jTMonto.setEnabled(false);

        if (corriente) {
            jTNIT.setEnabled(false);
            jDateFechaRetiro.setEnabled(false);
            jTMonto.setEnabled(true);

            jTNIT.setText("");
        } else if (ahorro) {

            jTNIT.setEnabled(false);
            jTNIT.setText("");
            jDateFechaRetiro.setEnabled(true);
            jTMonto.setEnabled(true);
        } else {
            jTNIT.setEnabled(true);
            jDateFechaRetiro.setEnabled(false);
            jTMonto.setEnabled(true);

            jTMonto.setText("");
        }
    }

}
