/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logica.Banco;
import logica.Cliente;
import logica.Empresa;
import persistencia.Persistencia;

/**
 * @author Alejandro
 * @author Shonny
 * @author Juan Carlos
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Banco miBanco;
    private Cliente miCliente;
    private Persistencia miPersistencia = new Persistencia();

    //true para empresa false para cliente

    /**
     *
     */
    public static boolean bandera;

    /**
     *
     */
    public static Empresa empresaSesion;

    /**
     *
     */
    public static Cliente clienteSesion;

    /**
     * Creates new form VentanaPrincipal
     * @throws java.text.ParseException
     */
    public VentanaPrincipal() throws ParseException {
        initComponents();
        setLocationRelativeTo(null);
        inicializarComponentes();

        try {//excepción
            llenarPersistencias();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, java.util.ResourceBundle.getBundle("properties/Banco").getString("EL ARCHIVO NO PUDO SER LEÍDO"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuarioSesion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuEmpresa = new javax.swing.JMenuItem();
        jMenuLogin = new javax.swing.JMenuItem();
        jMenuCuenta = new javax.swing.JMenu();
        jMenuIUsuario = new javax.swing.JMenuItem();
        jMenuUsuarioEmpresa = new javax.swing.JMenuItem();
        jMenuUsuarioAdmin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("properties/VentanaPrincipal"); // NOI18N
        jButton1.setText(bundle.getString("VentanaPrincipal.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuArchivo.setText(bundle.getString("ARCHIVO")); // NOI18N

        jMenu3.setText(bundle.getString("CREAR CUENTA")); // NOI18N

        jMenuCliente.setText(bundle.getString("CLIENTE")); // NOI18N
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuCliente);

        jMenuEmpresa.setText(bundle.getString("EMPRESA")); // NOI18N
        jMenuEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmpresaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuEmpresa);

        jMenuArchivo.add(jMenu3);

        jMenuLogin.setText(bundle.getString("LOGIN")); // NOI18N
        jMenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLoginActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuLogin);

        jMenuBar1.add(jMenuArchivo);

        jMenuCuenta.setText(bundle.getString("CUENTA")); // NOI18N

        jMenuIUsuario.setText(bundle.getString("USUARIO")); // NOI18N
        jMenuIUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIUsuarioActionPerformed(evt);
            }
        });
        jMenuCuenta.add(jMenuIUsuario);

        jMenuUsuarioEmpresa.setText(bundle.getString("EMPRESA")); // NOI18N
        jMenuUsuarioEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioEmpresaActionPerformed(evt);
            }
        });
        jMenuCuenta.add(jMenuUsuarioEmpresa);

        jMenuUsuarioAdmin.setText(bundle.getString("ADMIN")); // NOI18N
        jMenuUsuarioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioAdminActionPerformed(evt);
            }
        });
        jMenuCuenta.add(jMenuUsuarioAdmin);

        jMenuBar1.add(jMenuCuenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelUsuarioSesion)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton1)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuarioSesion)
                .addGap(100, 100, 100)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        //Inicializamos la ventana agregarjugador y le pasamos como parametro OpenDeAutralia para evitar que se reinicie los datos
        VentanaCrearCliente crearCliente = new VentanaCrearCliente(miBanco);
        crearCliente.setVisible(true);
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmpresaActionPerformed
        // TODO add your handling code here:
        VentanaCrearEmpresa crearEmpresa = new VentanaCrearEmpresa(miBanco);
        crearEmpresa.setVisible(true);
    }//GEN-LAST:event_jMenuEmpresaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        miPersistencia.aniadirArchivoClientes(miBanco.getClientes());
        miPersistencia.aniadirArchivoEmpresas(miBanco.getEmpresas());
        miPersistencia.aniadirArchivoNominas(miBanco.getNominas());
        miPersistencia.aniadirArchivoAhorros(miBanco.getAhorros());
        miPersistencia.aniadirArchivoCorrientes(miBanco.getCorrientes());
        miPersistencia.aniadirArchivoCDTs(miBanco.getCuentasCDTs());
    }//GEN-LAST:event_formWindowClosing

    private void jMenuUsuarioEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioEmpresaActionPerformed
        // TODO add your handling code here:
        VentanaCuentaEmpresa ventanaCuentaEmpresa = new VentanaCuentaEmpresa(miBanco);
        ventanaCuentaEmpresa.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioEmpresaActionPerformed

    private void jMenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLoginActionPerformed
        // TODO add your handling code here:
        VentanaLogin login = new VentanaLogin(miBanco);
        login.setVisible(true);
    }//GEN-LAST:event_jMenuLoginActionPerformed

    private void jMenuIUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIUsuarioActionPerformed
        // TODO add your handling code here:
        VentanaCuentaUsuario cuentaUsuario = new VentanaCuentaUsuario(miBanco);
        cuentaUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuIUsuarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        empresaSesion = null;
        clienteSesion = null;
        jLabelUsuarioSesion.setText(null);
        jMenuCuenta.setVisible(false);
        jMenuUsuarioAdmin.setVisible(true);
        jMenuUsuarioEmpresa.setVisible(true);
        jMenuIUsuario.setVisible(true);
        bandera = false;
        jMenuLogin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuUsuarioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioAdminActionPerformed
        // TODO add your handling code here:
        VentanaAdmin ventanaAdmin = new VentanaAdmin(miBanco);
        ventanaAdmin.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) { //NOI18N
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaPrincipal().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel jLabelUsuarioSesion;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCliente;
    public static javax.swing.JMenu jMenuCuenta;
    private javax.swing.JMenuItem jMenuEmpresa;
    public static javax.swing.JMenuItem jMenuIUsuario;
    public static javax.swing.JMenuItem jMenuLogin;
    public static javax.swing.JMenuItem jMenuUsuarioAdmin;
    public static javax.swing.JMenuItem jMenuUsuarioEmpresa;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @throws IOException
     * @throws ParseException
     */
    public void llenarPersistencias() throws IOException, ParseException {
        miBanco = new Banco(miPersistencia.inicializarAtributosClientes(), miPersistencia.inicializarAtributosEmpresa());
        miPersistencia.inicializarAtributosNominas(miBanco);
        miPersistencia.inicializarAtributosAhorros(miBanco);
        miPersistencia.inicializarAtributosCorrientes(miBanco);
        miPersistencia.inicializarAtributosCDTs(miBanco);
    }

    /**
     *
     */
    public void inicializarComponentes() {
        jLabelUsuarioSesion.setVisible(false);
        jMenuCuenta.setVisible(false);
    }
}
