/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Enumeracion.Permiso;
import java.util.Date;
import javax.swing.JOptionPane;
import logica.Ahorro;
import logica.Banco;
import logica.Cliente;
import logica.Corriente;
import logica.Empresa;
import logica.Nomina;
import static vista.VentanaPrincipal.clienteSesion;

/**
 * @author Alejandro
 * @author Shonny
 * @author Juan Carlos
 */
public class VentanaCrearCuentaAdmin extends javax.swing.JFrame {

    private Banco miBanco;
    private Ahorro miAhorro;
    private Corriente miCorriente;
    private Nomina miNomina;
    private Empresa miEmpresa;
    private Cliente miCliente;
    private String id;

    /**
     * Creates new form VentanaCrearCuenta
     * @param ban
     */
    public VentanaCrearCuentaAdmin(Banco ban, String id) {
        miBanco = ban;
        this.id = id;
        initComponents();
        setLocationRelativeTo(null);
        
        miCliente=miBanco.buscarCliente(id);

        jTNIT.setEnabled(false);
        jDateFechaRetiro.setEnabled(false);
        jTMonto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCuentas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioAhorro = new javax.swing.JRadioButton();
        jRadioCorriente = new javax.swing.JRadioButton();
        jRadioNomina = new javax.swing.JRadioButton();
        jLMonto = new javax.swing.JLabel();
        jLNIT = new javax.swing.JLabel();
        jLFechaRetiro = new javax.swing.JLabel();
        jTMonto = new javax.swing.JTextField();
        jTNIT = new javax.swing.JTextField();
        jDateFechaRetiro = new com.toedter.calendar.JDateChooser();
        jBCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Crear Cuenta"));

        buttonGroupCuentas.add(jRadioAhorro);
        jRadioAhorro.setText("Ahorro");
        jRadioAhorro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioAhorroItemStateChanged(evt);
            }
        });

        buttonGroupCuentas.add(jRadioCorriente);
        jRadioCorriente.setText("Corriente");
        jRadioCorriente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioCorrienteItemStateChanged(evt);
            }
        });
        jRadioCorriente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioCorrienteActionPerformed(evt);
            }
        });

        buttonGroupCuentas.add(jRadioNomina);
        jRadioNomina.setText("Nomina");
        jRadioNomina.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioNominaItemStateChanged(evt);
            }
        });
        jRadioNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNominaActionPerformed(evt);
            }
        });

        jLMonto.setText("Monto:");

        jLNIT.setText("NIT:");

        jLFechaRetiro.setText("Fecha Retiro:");

        jBCrearCuenta.setText("Crear Cuenta");
        jBCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioAhorro)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jRadioCorriente)
                        .addGap(46, 46, 46)
                        .addComponent(jRadioNomina))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMonto)
                            .addComponent(jLNIT))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNIT)
                            .addComponent(jTMonto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLFechaRetiro)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFechaRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jBCrearCuenta)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioAhorro)
                    .addComponent(jRadioCorriente)
                    .addComponent(jRadioNomina))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMonto)
                    .addComponent(jTMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNIT)
                    .addComponent(jTNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLFechaRetiro)
                    .addComponent(jDateFechaRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jBCrearCuenta)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearCuentaActionPerformed
        // TODO add your handling code here:
        if (validarDatos().equals("")) {
            
            String nit = jTNIT.getText();
            Date fechaCreacion = new Date();

            if (jRadioAhorro.isSelected()) {
                //selecciono ahorro
                double monto = Double.parseDouble(jTMonto.getText());
                Date fechaRetiro = jDateFechaRetiro.getCalendar().getTime();
                String numeroAhorro = "AH-" + (miBanco.numeroTotalAhorro() + 1);
                miAhorro = new Ahorro(fechaRetiro, monto, numeroAhorro, fechaCreacion);
                boolean agregarAhorro = miCliente.agregarCuentaAhorro(miAhorro);
                //revisar lo hizo juank, los usuarios no tienen numeros bancario tienen cuentas...
                miCliente.setNumeroBancario(numeroAhorro);

                //Mostramos mensaje de que se agrego o no la cuneta de ahorros
                if (agregarAhorro) {
                    JOptionPane.showMessageDialog(null, "La cuenta de Ahorros se creo");
//                    VentanaCuentaUsuario.llenarTablaAhorro();
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede crear la cuenta de Ahorros");
                }

            } else if (jRadioCorriente.isSelected()) {
                //selecciono corriente
                double monto = Double.parseDouble(jTMonto.getText());
                String numeroCorriente = "CO-" + (miBanco.numeroTotalCorriente() + 1);
                miCorriente = new Corriente(monto, numeroCorriente, fechaCreacion);

                boolean agregarCorriente = miCliente.agregarCuentaCorriente(miCorriente);
                miCliente.setNumeroBancario(numeroCorriente);

                //Mostramos mensaje de que se agrego o no la cuneta de ahorros
                if (agregarCorriente) {
                    JOptionPane.showMessageDialog(null, "La cuenta Corriente se creo");
//                    VentanaCuentaUsuario.llenarTablaCorriente();
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede crear la cuenta Corriente");
                }

            } else {
                //selecciono nomina
                miEmpresa = miBanco.buscarEmpresa(nit);

                if (miEmpresa != null) {
                    String numeroNomina = "NO-" + (miBanco.numeroTotalNomina() + 1);
                    miNomina = new Nomina(miEmpresa, miCliente, 0, numeroNomina,fechaCreacion);
                    
                    boolean agregarNomina = miCliente.agregarCuentaNomina(miNomina);
                    
                    if (!agregarNomina) {
                        JOptionPane.showMessageDialog(null, "La cuenta Nomina se creo");
//                        VentanaCuentaUsuario.llenarTablaNomina();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se puede crear la cuenta Nomina");

                    }
                    
                } else {
                    JOptionPane.showMessageDialog(null, "La empresa no existe");
                }

            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "ERROR!!! \n" + validarDatos(), "Validando Datos",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBCrearCuentaActionPerformed

    private void jRadioNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioNominaActionPerformed

    private void jRadioNominaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioNominaItemStateChanged
        //        if (jRadioNomina.isSelected()) {
            jTNIT.setEnabled(true);
            jDateFechaRetiro.setEnabled(false);
            jTMonto.setEnabled(false);

            jTMonto.setText("");
//            jDateFechaRetiro.setCalendar(null);
            //        }        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioNominaItemStateChanged

    private void jRadioCorrienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioCorrienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioCorrienteActionPerformed

    private void jRadioCorrienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioCorrienteItemStateChanged
        // TODO add your handling code here:
        //                if (jRadioCorriente.isSelected()) {
            jTNIT.setEnabled(false);
            jDateFechaRetiro.setEnabled(false);
            jTMonto.setEnabled(true);

            jTNIT.setText("");
//            jDateFechaRetiro.setCalendar(null);
            //        }
    }//GEN-LAST:event_jRadioCorrienteItemStateChanged

    private void jRadioAhorroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioAhorroItemStateChanged
        // TODO add your handling code here:
        //        if (jRadioAhorro.isSelected()) {
            jTNIT.setEnabled(false);
            jTNIT.setText("");
            jDateFechaRetiro.setEnabled(true);
            jTMonto.setEnabled(true);
            //        }
    }//GEN-LAST:event_jRadioAhorroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCrearCuentaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCrearCuentaAdmin(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCuentas;
    private javax.swing.JButton jBCrearCuenta;
    private com.toedter.calendar.JDateChooser jDateFechaRetiro;
    private javax.swing.JLabel jLFechaRetiro;
    private javax.swing.JLabel jLMonto;
    public static javax.swing.JLabel jLNIT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioAhorro;
    private javax.swing.JRadioButton jRadioCorriente;
    private javax.swing.JRadioButton jRadioNomina;
    private javax.swing.JTextField jTMonto;
    private javax.swing.JTextField jTNIT;
    // End of variables declaration//GEN-END:variables

    private String validarDatos() {
        String msj = "";
        if (!jRadioAhorro.isSelected() && !jRadioCorriente.isSelected() && !jRadioNomina.isSelected()) {
            msj += "Por favor Seleccione un tipo de cuenta";
        }
        if (jRadioAhorro.isSelected()) {
            if (jTMonto.getText().equals("")) {
                msj += "Por favor digite el Monto con el que va a empezar la cuenta de ahorro.\n";
            }
            if (jDateFechaRetiro.getCalendar() == null) {//Si jDateFechaNacimiento esta vacio
                msj += "Por favor seleccione una fecha.";
            }
        }

        if (jRadioCorriente.isSelected()) {
            if (jTMonto.getText().equals("")) {//Si jTMonto esta vacio
                msj += "Por favor digite el Monto con el que va a empezar la cuenta corriente.\n";
            }
        }

        if (jRadioNomina.isSelected()) {
            if (jTNIT.getText().equals("")) {//Si jTNIT esta vacio
                msj += "Por favor digite el NIT de la empresa.";
            }
        }
        return msj;
    }

}
